terminate called after throwing an instance of 'std::runtime_error'
  what():  S2I conversion error: abc
Aborted
